### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by AguirreNicolas** [Dubrzr/mimic3-scripts#1]
Hi @Dubrzr ,

Great work! 

Hi used 'mimi.pg_dump'. I would like to know if you have any publication to referenciate where you used it?

Best regards

Nicolas

**Comment by Dubrzr** [comment]
Hi @AguirreNicolas, 

I don't have publications for reference. But you can cite this repository if you want.

Thanks,
Best

**Comment by AguirreNicolas** [comment]
Bien sûr, pas de problème!

Cordialement,

Nicolas

**Comment by Dubrzr** [comment]
Bonne continuation ;)
